// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi5IxE15kvmUs_5EDJEgO14UCCMI_IOPA',
    appId: '1:394593759164:android:b9a16c0a31c406dbda45b9',
    messagingSenderId: '394593759164',
    projectId: 'quick-cart-deba5',
    storageBucket: 'quick-cart-deba5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_EYLKAzPXhipnLzSGCfcczaHhC6lfYB8',
    appId: '1:394593759164:ios:56bfb1111cf97137da45b9',
    messagingSenderId: '394593759164',
    projectId: 'quick-cart-deba5',
    storageBucket: 'quick-cart-deba5.appspot.com',
    androidClientId: '394593759164-spj705hrt62971o78ebb84kcf4lrvdd2.apps.googleusercontent.com',
    iosClientId: '394593759164-iu6equsiik9ajj8ht392v4vp2lqjp4oi.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChuWNmIwp9jQyaWUJL9Jzu9AP1W8uhGTk',
    appId: '1:394593759164:web:7a6e4142c9393464da45b9',
    messagingSenderId: '394593759164',
    projectId: 'quick-cart-deba5',
    authDomain: 'quick-cart-deba5.firebaseapp.com',
    storageBucket: 'quick-cart-deba5.appspot.com',
  );

}